# Generated by Django 3.0.4 on 2020-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='realtor_email',
            field=models.CharField(default='richard@mail.ru', max_length=100),
            preserve_default=False,
        ),
    ]
